app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

richardpq_admin:
    resource: "@RichardPQAdminBundle/Controller/"
    type:     annotation